// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxwojEO8t2PD_qBsh99XQD6iywsubBhqU',
    appId: '1:233843702285:web:a8c4a20ea4a37b104a7344',
    messagingSenderId: '233843702285',
    projectId: 'hotelmarrakech-kwh',
    authDomain: 'hotelmarrakech-kwh.firebaseapp.com',
    storageBucket: 'hotelmarrakech-kwh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMIqjRaQIMIEtyiF4W63qL4lTDAys3mQ',
    appId: '1:233843702285:android:3c14e721b66dd6044a7344',
    messagingSenderId: '233843702285',
    projectId: 'hotelmarrakech-kwh',
    storageBucket: 'hotelmarrakech-kwh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6TnCOJAvfE_eOpJlRotqtsJrsIEK8xTk',
    appId: '1:233843702285:ios:73b6add3ae0da4644a7344',
    messagingSenderId: '233843702285',
    projectId: 'hotelmarrakech-kwh',
    storageBucket: 'hotelmarrakech-kwh.appspot.com',
    iosClientId: '233843702285-0augi4hitv41bn16squ4ao7vaji9e2fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocioMarakech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6TnCOJAvfE_eOpJlRotqtsJrsIEK8xTk',
    appId: '1:233843702285:ios:73b6add3ae0da4644a7344',
    messagingSenderId: '233843702285',
    projectId: 'hotelmarrakech-kwh',
    storageBucket: 'hotelmarrakech-kwh.appspot.com',
    iosClientId: '233843702285-0augi4hitv41bn16squ4ao7vaji9e2fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocioMarakech',
  );
}
